package com.bellamyphan.finora_spring.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(
        name = "bank_groups",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = { "name", "user_id" })
        }
)
public class BankGroup {

    @Id
    @Column(name = "id", nullable = false, length = 10)
    private String id; // NanoID 10-char generated by Java

    @Column(name = "name", nullable = false, length = 100)
    @NotBlank(message = "Bank group name is required")
    private String name;

    @ManyToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "user_id", nullable = false, foreignKey = @ForeignKey(name = "fk_bank_groups_users"))
    private User user;
}