package com.bellamyphan.finora_spring.entity;

import com.bellamyphan.finora_spring.constant.BankTypeEnum;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@Entity
@Table(name = "bank_types")
public class BankType {

    @Id
    @Column(name = "id", nullable = false, length = 10)
    private String id; // NanoID 10-char generated by Java

    @Enumerated(EnumType.STRING) // Store enum as string
    @Column(name = "type", nullable = false, unique = true, length = 15)
    @NotNull(message = "Bank type is required")
    private BankTypeEnum type;

    // Constructor with only enum (id generated separately)
    public BankType(BankTypeEnum type) {
        this.type = type;
    }
}
