package com.bellamyphan.finora_spring.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "bank_types")
@Data
@NoArgsConstructor
public class BankType {

    @Id
    @Column(name = "id", nullable = false, length = 10)
    private String id; // NanoID 10-char generated by Java

    @Enumerated(EnumType.STRING) // Store enum as string
    @Column(name = "type", nullable = false, unique = true, length = 50)
    @NotBlank(message = "Bank type is required")
    private BankTypeEnum type;

    // Constructor with both id and enum
    public BankType(String id, BankTypeEnum type) {
        this.id = id;
        this.type = type;
    }

    // Constructor with only enum (id generated separately)
    public BankType(BankTypeEnum type) {
        this.type = type;
    }
}
