package com.bellamyphan.finora_spring.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@NoArgsConstructor
@Entity
@Table(name = "banks")
public class Bank {

    @Id
    @Column(name = "id", nullable = false, length = 10)
    private String id; // NanoID 10-char generated by Java

    @Column(name = "name", nullable = false, length = 100)
    @NotBlank(message = "Bank name is required")
    private String name;

    @Column(name = "opening_date", nullable = false)
    private LocalDate openingDate;

    @Column(name = "closing_date")
    private LocalDate closingDate;

    @ManyToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "type_id", nullable = false, foreignKey = @ForeignKey(name = "fk_banks_bank_types"))
    private BankType type;

    @ManyToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "user_id", nullable = false, foreignKey = @ForeignKey(name = "fk_banks_users"))
    private User user;

    // Constructor with all fields except id (id can be generated separately)
    public Bank(String name, LocalDate openingDate, LocalDate closingDate, BankType type, User user) {
        this.name = name;
        this.openingDate = openingDate;
        this.closingDate = closingDate;
        this.type = type;
        this.user = user;
    }
}
