package com.bellamyphan.finora_spring.entity;

import com.bellamyphan.finora_spring.constant.TransactionTypeEnum;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "transaction_types")
@Data
@NoArgsConstructor
public class TransactionType {

    @Id
    @Column(name = "id", nullable = false, length = 10)
    private String id; // NanoID 10-char, generated by Java

    @Enumerated(EnumType.STRING) // Store enum as string in DB
    @Column(name = "type", nullable = false, unique = true, length = 50)
    @NotNull(message = "Transaction type is required")
    private TransactionTypeEnum type;

    // Constructor with id
    public TransactionType(String id, TransactionTypeEnum type) {
        this.id = id;
        this.type = type;
    }

    // Constructor without id (NanoID can be generated)
    public TransactionType(TransactionTypeEnum type) {
        this.type = type;
    }
}